[package]
name = "pipeline-app"
version.workspace = true
edition.workspace = true
rust-version.workspace = true

[dependencies]
eframe.workspace = true
pipeline-domain = { path = "../pipeline-domain" }
pipeline-engine = { path = "../pipeline-engine" }
pipeline-terminal = { path = "../pipeline-terminal" }
directories = "6"
